[2024-08-17T16:16:46.101+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [queued]>
[2024-08-17T16:16:46.106+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [queued]>
[2024-08-17T16:16:46.106+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-08-17T16:16:46.114+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): obtain_data> on 2024-08-17 15:47:53.714343+00:00
[2024-08-17T16:16:46.119+0000] {standard_task_runner.py:60} INFO - Started process 263 to run task
[2024-08-17T16:16:46.121+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'obtain_data', 'manual__2024-08-17T15:47:53.714343+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp75vwnqr8']
[2024-08-17T16:16:46.123+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask obtain_data
[2024-08-17T16:16:46.155+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.obtain_data manual__2024-08-17T15:47:53.714343+00:00 [running]> on host ab9e9042f5d0
[2024-08-17T16:16:46.208+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='obtain_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T15:47:53.714343+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T15:47:53.714343+00:00'
[2024-08-17T16:16:51.094+0000] {logging_mixin.py:188} INFO - Datos guardados en PostgreSQL en la tabla data
[2024-08-17T16:16:51.096+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-17T16:16:51.102+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl, task_id=obtain_data, execution_date=20240817T154753, start_date=20240817T161646, end_date=20240817T161651
[2024-08-17T16:16:51.146+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-17T16:16:51.156+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
